// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0rVZ_t83kEeHu1UAn7dLdVAHTA7dFA3M',
    appId: '1:856489135805:web:9d43b5a3da4f870f6731d4',
    messagingSenderId: '856489135805',
    projectId: 'taht-bety',
    authDomain: 'taht-bety.firebaseapp.com',
    storageBucket: 'taht-bety.firebasestorage.app',
    measurementId: 'G-85Z2VBED09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzpwK1jy6JI84ooPRjSKiXsvAxtIQq9vU',
    appId: '1:856489135805:android:c2c968704c956a0b6731d4',
    messagingSenderId: '856489135805',
    projectId: 'taht-bety',
    storageBucket: 'taht-bety.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBMxBv2-RvQEqbpaJPBJOKRpfekpLI0RY',
    appId: '1:856489135805:ios:94b9448697f3c93b6731d4',
    messagingSenderId: '856489135805',
    projectId: 'taht-bety',
    storageBucket: 'taht-bety.firebasestorage.app',
    iosBundleId: 'com.example.tahtBety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBMxBv2-RvQEqbpaJPBJOKRpfekpLI0RY',
    appId: '1:856489135805:ios:94b9448697f3c93b6731d4',
    messagingSenderId: '856489135805',
    projectId: 'taht-bety',
    storageBucket: 'taht-bety.firebasestorage.app',
    iosBundleId: 'com.example.tahtBety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0rVZ_t83kEeHu1UAn7dLdVAHTA7dFA3M',
    appId: '1:856489135805:web:5d6250f26d54cbfb6731d4',
    messagingSenderId: '856489135805',
    projectId: 'taht-bety',
    authDomain: 'taht-bety.firebaseapp.com',
    storageBucket: 'taht-bety.firebasestorage.app',
    measurementId: 'G-29Y1GKB58J',
  );
}
